import "~/styles/globals.css";

import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation";
import { Footer } from "~/components/footer";
import { Header } from "~/components/header";
import { Toaster } from "~/components/ui/toaster";
import Providers from "~/providers";
import { authOptions } from "~/server/auth";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/api/auth/signin");
  }
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={`font-sans ${inter.variable} flex h-full flex-col`}>
        <Providers>
          <Header />
          <main className="flex-grow border">{children}</main>
          {modal}
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
